name: flutter_perfect_ddd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.2
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  logger: ^2.3.0
  retrofit: ^4.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  retrofit_generator: ^8.1.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Define entry points for different environments
  # targets:
  #   $default:
  #     main: lib/main_dev.dart
  #   uat:
  #     main: lib/main_uat.dart
  #   prod:
  #     main: lib/main_prod.dart
