name: flutter_perfect_ddd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  freezed: ^2.5.2
  go_router: ^14.2.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
